### ISSUE TITLE
node dev doesn't work on Windows

### ISSUE THREAD

**Issue by AndyCormack** [FrontendMasters/remix-fundamentals#2] opened 2022-08-02 15:56 UTC
Due to `path` outputting `\\` instead of `/` for paths on Windows this breaks currently, need to account for it in [relativePath](https://github.com/FrontendMasters/remix-fundamentals/blob/main/scripts/utils/utils.ts#L114) and [fullPath](https://github.com/FrontendMasters/remix-fundamentals/blob/main/scripts/utils/utils.ts#L116).

I've just temp worked around it by adding a replace on the end of each `.replace('\\', '/')` but there's probably a cleaner way.

**Comment by technologic808** [comment] 2022-08-02 16:28
works for me 

![image](https://user-images.githubusercontent.com/20627603/182425616-e3dcb8b0-ef64-4bf7-b3e1-8a05432f666f.png)

**Comment by AndyCormack** [comment] 2022-08-02 23:02
My fault for not being more clear, I mean when you type an individual numbered exercise as the param. e.g. `node dev 1`

I get something like this until I tweaked the utils file 
![image](https://user-images.githubusercontent.com/2339384/182487936-166071c3-a957-459c-bdd2-72897c34a933.png)

**Comment by technologic808** [comment] 2022-08-03 07:26
Ah, I see. I can confirm that I am also getting the same error with this step

**Comment by giancarlosisasi** [comment] 2022-09-28 22:30
same here 😢

**Comment by dtauer** [comment] 2022-10-04 13:04
Sorry about this! We're working on a fix for the repo. In the meantime, running `node dev` (without specifying an exercise) should work. It will present you with a list (see screenshot above). You can use your arrow keys to select the exercise to run.

**Comment by dtauer** [comment] 2022-10-04 18:32
This should be fixed now. We also removed the Node 14 requirement and now are requiring Node 16+

**Closed as completed by dtauer** 2022-10-04 18:32 UTC
